version: '3.8'

services:
  rankly-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rankly-ai-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./prisma:/app/prisma
      - ./uploads:/app/uploads
      - ./backups:/app/backups
